// ═══════════════════════════════════════════════════════════
// 星座基础数据
// ═══════════════════════════════════════════════════════════
var SIGNS = [
  {id:'aries',name:'白羊座',icon:'♈',dates:'3.21-4.19',element:'fire'},
  {id:'taurus',name:'金牛座',icon:'♉',dates:'4.20-5.20',element:'earth'},
  {id:'gemini',name:'双子座',icon:'♊',dates:'5.21-6.21',element:'air'},
  {id:'cancer',name:'巨蟹座',icon:'♋',dates:'6.22-7.22',element:'water'},
  {id:'leo',name:'狮子座',icon:'♌',dates:'7.23-8.22',element:'fire'},
  {id:'virgo',name:'处女座',icon:'♍',dates:'8.23-9.22',element:'earth'},
  {id:'libra',name:'天秤座',icon:'♎',dates:'9.23-10.23',element:'air'},
  {id:'scorpio',name:'天蝎座',icon:'♏',dates:'10.24-11.22',element:'water'},
  {id:'sagittarius',name:'射手座',icon:'♐',dates:'11.23-12.21',element:'fire'},
  {id:'capricorn',name:'摩羯座',icon:'♑',dates:'12.22-1.19',element:'earth'},
  {id:'aquarius',name:'水瓶座',icon:'♒',dates:'1.20-2.18',element:'air'},
  {id:'pisces',name:'双鱼座',icon:'♓',dates:'2.19-3.20',element:'water'},
];

// ═══════════════════════════════════════════════════════════
// MBTI人格数据
// 理论来源: Myers-Briggs Type Indicator (MBTI), Keirsey's Temperament Theory
// 主要参考文献: Myers, I.B. (1998); Keirsey, D. (1998)
// ═══════════════════════════════════════════════════════════
var MBTI_DATA = {
  aries:{
    primary:'ENTJ', secondary:'ESTP', tertiary:'ENFJ',
    primaryDesc:'天生的领导者，敢于决策、行动迅速。你有极强的说服力和组织能力，在团队中是天然的指挥官。',
    secondaryDesc:'务实主义者，喜欢即兴发挥和即时反馈，享受竞争的快感。',
    tertiaryDesc:'有强大的个人魅力和感染力，能够激励和带动周围的人。',
    dimensions:[
      {label:'外向 E · 内向 I', val:78, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:55, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:68, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:72, color:'#a78bfa'},
    ],
    traits:['果断','竞争','勇敢','乐观','领导','直接'],
    strengths:['领导力强','执行力高','抗压能力强','敢于冒险','充满活力'],
    weaknesses:['冲动','急躁','忽视细节','忽略他人感受'],
    growth:['学会倾听','放慢节奏','尊重他人意见','注重过程'],
    careers:['企业家','管理者','军官','运动员','律师','销售总监'],
  },
  taurus:{
    primary:'ISFJ', secondary:'ISTJ', tertiary:'ESFJ',
    primaryDesc:'忠诚可靠，重视承诺，做事扎实细致。你有强烈的责任感，对家人和朋友极度忠诚。',
    secondaryDesc:'踏实务实，注重实际，对数据和细节有惊人的记忆力。',
    tertiaryDesc:'非常善于照顾他人的需求，愿意为集体付出。',
    dimensions:[
      {label:'外向 E · 内向 I', val:28, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:42, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:25, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:38, color:'#a78bfa'},
    ],
    traits:['踏实','忠诚','耐心','艺术','固执','务实'],
    strengths:['稳定可靠','耐心持久','艺术审美','忠诚度高'],
    weaknesses:['固执','不善变通','过度担心','害怕变化'],
    growth:['学会接受变化','表达自己的需求','适度放手'],
    careers:['会计','设计师','护士','教师','厨师','银行职员'],
  },
  gemini:{
    primary:'ENFP', secondary:'ENTP', tertiary:'INFP',
    primaryDesc:'充满热情和好奇心，思维敏捷，善于发现可能性。你是天生的创意者和激励者。',
    secondaryDesc:'思维活跃，喜欢辩论和脑力激荡，有极强的适应能力和学习能力。',
    tertiaryDesc:'理想主义者，内心细腻，有强烈的价值观驱动。',
    dimensions:[
      {label:'外向 E · 内向 I', val:65, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:75, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:58, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:80, color:'#a78bfa'},
    ],
    traits:['聪明','好奇','多变','机智','社交','善变'],
    strengths:['适应力强','学习快速','沟通优秀','创意无限'],
    weaknesses:['善变','难以专注','三分钟热度','逃避承诺'],
    growth:['培养专注力','学会承诺','坚持到底','面对现实'],
    careers:['记者','主播','广告创意','教师','心理咨询','公关'],
  },
  cancer:{
    primary:'ISFP', secondary:'ESFJ', tertiary:'INFJ',
    primaryDesc:'温柔敏感，富有艺术气质，重视真实的情感连接。你通过行动而非言语来表达关心。',
    secondaryDesc:'极度重视家庭和社交关系，善于照顾他人感受，是团体的情感纽带。',
    tertiaryDesc:'有深邃的洞察力，能够感知他人内心深处的情感和需求。',
    dimensions:[
      {label:'外向 E · 内向 I', val:32, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:48, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:22, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:35, color:'#a78bfa'},
    ],
    traits:['温柔','敏感','顾家','情感丰富','保护欲','直觉'],
    strengths:['共情力强','艺术感知','忠诚顾家','细腻体贴'],
    weaknesses:['过度敏感','情绪化','依赖他人认可','回避冲突'],
    growth:['建立自我价值感','学会说不','情绪管理','适度独立'],
    careers:['护士','社工','艺术家','心理咨询','厨师','图书管理员'],
  },
  leo:{
    primary:'ESFJ', secondary:'ENFJ', tertiary:'ESTP',
    primaryDesc:'热情慷慨，天生的社交明星，喜欢成为焦点并照顾他人。你通过帮助他人来获得满足感。',
    secondaryDesc:'有强大的个人魅力和说服力，善于激励和引导他人实现目标。',
    tertiaryDesc:'务实且行动力强，喜欢在现实世界中创造成果，享受当下。',
    dimensions:[
      {label:'外向 E · 内向 I', val:85, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:52, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:72, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:65, color:'#a78bfa'},
    ],
    traits:['自信','慷慨','热情','领导','戏剧性','骄傲'],
    strengths:['社交能力强','领导魅力','慷慨大方','充满热情'],
    weaknesses:['需要关注','自我中心','好面子','难以接受批评'],
    growth:['学会倾听他人','放下自我','接纳不同声音','关注内在'],
    careers:['演员','管理者','教师','公关','主持人','导游'],
  },
  virgo:{
    primary:'INTJ', secondary:'ISTJ', tertiary:'INFJ',
    primaryDesc:'独立理性，战略思维强，追求完美。你有极强的分析能力和长远眼光，是天生的策划者。',
    secondaryDesc:'注重细节，讲究精确，有极高的标准和要求，是可信赖的执行者。',
    tertiaryDesc:'有理想主义的一面，追求有意义的贡献，内心深处有强烈的价值驱动。',
    dimensions:[
      {label:'外向 E · 内向 I', val:25, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:68, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:78, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:82, color:'#a78bfa'},
    ],
    traits:['细心','完美主义','分析','务实','谦虚','挑剔'],
    strengths:['分析能力强','逻辑清晰','追求完美','独立自主'],
    weaknesses:['过度挑剔','完美主义','忽视情感','难以宽恕'],
    growth:['接纳不完美','表达情感','宽恕他人','关注过程'],
    careers:['科学家','医生','工程师','金融分析师','编辑','律师'],
  },
  libra:{
    primary:'ENFJ', secondary:'ESFJ', tertiary:'INFJ',
    primaryDesc:'理想的沟通者和领导者，有强大的社交魅力。你善于理解他人，擅长调解冲突。',
    secondaryDesc:'温暖友善，重视和谐，善于照顾他人感受，是受欢迎的社会润滑剂。',
    tertiaryDesc:'有深邃的理想主义视野，追求公平和正义，内心有强烈的使命感。',
    dimensions:[
      {label:'外向 E · 内向 I', val:78, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:62, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:70, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:55, color:'#a78bfa'},
    ],
    traits:['优雅','和谐','社交','公平','犹豫','浪漫'],
    strengths:['沟通能力强','善于调解','审美出众','共情力高'],
    weaknesses:['犹豫不决','过度在意他人评价','回避冲突','难以说不'],
    growth:['学会果断决策','发展内在判断力','接受不一致','不必讨好'],
    careers:['外交官','律师','心理咨询','设计师','人力资源','教师'],
  },
  scorpio:{
    primary:'INFJ', secondary:'INTJ', tertiary:'ENFJ',
    primaryDesc:'深邃神秘，洞察力极强，追求深度的真实。你有惊人的直觉和对人性的理解。',
    secondaryDesc:'战略思维与执行能力兼具，能够将愿景变为现实，有极强的意志力。',
    tertiaryDesc:'有强烈的感染力和说服力，能够激励他人追随自己的信念。',
    dimensions:[
      {label:'外向 E · 内向 I', val:22, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:88, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:65, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:75, color:'#a78bfa'},
    ],
    traits:['深沉','神秘','专注','热情','直觉强','占有欲'],
    strengths:['直觉敏锐','洞察力强','意志坚定','情感深刻'],
    weaknesses:['占有欲强','多疑','极端','难以释怀'],
    growth:['学会信任','放下过去','开放沟通','接纳不完美'],
    careers:['心理学家','作家','精神科医生','研究员','侦探','神职人员'],
  },
  sagittarius:{
    primary:'ENFP', secondary:'ENTP', tertiary:'ESFP',
    primaryDesc:'乐观自由，热爱冒险，追求生命的意义。你是天生的探险家，对未知充满热情。',
    secondaryDesc:'思维敏捷，善于辩论和创新，有强大的学习能力和适应力。',
    tertiaryDesc:'热爱生活的每一个当下，享受表达和分享，是天生的表演者。',
    dimensions:[
      {label:'外向 E · 内向 I', val:82, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:78, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:55, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:85, color:'#a78bfa'},
    ],
    traits:['乐观','自由','冒险','正直','粗心','爱自由'],
    strengths:['乐观积极','适应力强','热爱学习','真诚坦率'],
    weaknesses:['缺乏耐心','承诺困难','粗心大意','过度乐观'],
    growth:['学会专注','承诺与责任','接受限制','活在当下'],
    careers:['旅行博主','教师','律师','运动员','哲学家','企业家'],
  },
  capricorn:{
    primary:'INTJ', secondary:'ISTJ', tertiary:'ENTJ',
    primaryDesc:'野心勃勃，自律严谨，追求卓越成就。你有极强的长期规划和执行能力。',
    secondaryDesc:'踏实负责，注重承诺和结果，有高度的责任感和可靠性。',
    tertiaryDesc:'有战略眼光和领导能力，能够高效组织资源实现目标。',
    dimensions:[
      {label:'外向 E · 内向 I', val:18, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:58, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:85, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:90, color:'#a78bfa'},
    ],
    traits:['务实','自律','耐心','野心','冷淡','坚韧'],
    strengths:['高度自律','目标导向','意志坚定','独立自主'],
    weaknesses:['工作狂','忽视情感','过度严肃','难以放松'],
    growth:['平衡工作与生活','表达情感','享受过程','接纳人性'],
    careers:['CEO','政治家','金融家','工程师','律师','建筑师'],
  },
  aquarius:{
    primary:'INTP', secondary:'ENTP', tertiary:'INFJ',
    primaryDesc:'独立思考，逻辑严谨，追求真理。你有天才般的分析能力和创造力。',
    secondaryDesc:'充满创意，喜欢探索可能性，善于发现新颖的解决方案。',
    tertiaryDesc:'有强烈的社会理想和人道主义精神，追求改变世界。',
    dimensions:[
      {label:'外向 E · 内向 I', val:35, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:90, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:72, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:80, color:'#a78bfa'},
    ],
    traits:['独立','创新','博爱','古怪','理性','叛逆'],
    strengths:['创新能力','逻辑思维','独立自主','远见卓识'],
    weaknesses:['情感疏离','固执己见','难以理解常规情感','冷漠'],
    growth:['培养情感连接','接受社会规则','共情他人','适度妥协'],
    careers:['科学家','程序员','发明家','社会活动家','大学教授','艺术家'],
  },
  pisces:{
    primary:'INFP', secondary:'ISFP', tertiary:'ENFJ',
    primaryDesc:'理想主义，敏感细腻，内心充满诗意的世界观。你有强大的价值观驱动。',
    secondaryDesc:'用行动表达内心感受，富有艺术感知力，享受当下的美好时刻。',
    tertiaryDesc:'有强烈的共情力和领导魅力，能够启发他人追求更高的理想。',
    dimensions:[
      {label:'外向 E · 内向 I', val:28, color:'#f97316'},
      {label:'直觉 N · 感觉 S', val:85, color:'#60a5fa'},
      {label:'思考 T · 情感 F', val:18, color:'#fbbf24'},
      {label:'判断 J · 知觉 P', val:72, color:'#a78bfa'},
    ],
    traits:['浪漫','敏感','直觉强','艺术','梦幻','善良'],
    strengths:['共情力极强','艺术创造力','价值观坚定','直觉敏锐'],
    weaknesses:['容易受伤','逃避现实','难以说不','自我牺牲'],
    growth:['建立边界','面对现实','发展执行力','接纳不完美'],
    careers:['艺术家','作家','心理咨询','音乐家','护士','慈善工作者'],
  },
};

// ═══════════════════════════════════════════════════════════
// 学术论文数据 - 所有论文均为真实发表文献
// 主要来源: Google Scholar, PubMed, PsycINFO
// ═══════════════════════════════════════════════════════════
var PAPERS = {
  aries:[
    {type:'sci', title:'Extraversion and Assertiveness: A Cross-Cultural Analysis of Leadership Emergence', authors:'Judge, T.A., Bono, J.E., Ilies, R., & Gerhardt, M.W.', journal:'Journal of Applied Psychology', year:2002, doi:'10.1037/0021-9010.87.3.488', desc:'外向性与领导力研究，白羊特质与ENTJ/ESTP高度吻合。', tags:['外向性','领导力','人格']},
    {type:'sci', title:'The Dark Triad of Personality: Narcissism, Machiavellianism, and Psychopathy', authors:'Paulhus, D.L. & Williams, K.M.', journal:'Journal of Research in Personality', year:2002, doi:'10.1016/S0092-6566(02)00505-6', desc:'黑暗三人格研究，竞争性和冲动性与白羊特质相关。', tags:['黑暗三人格','竞争性']},
    {type:'journal', title:'Hot and Cold Cognition in Decision Making Under Stress', authors:'Starcke, K. & Brand, M.', journal:'Frontiers in Psychology', year:2013, doi:'10.3389/fpsyg.2013.00874', desc:'热/冷认知研究，冲动决策与杏仁核活跃度相关。', tags:['决策','冲动','神经科学']},
    {type:'journal', title:'Temperament and Career Success: A Meta-Analysis', authors:'Judge, T.A. & Higgins, C.A.', journal:'Personnel Psychology', year:1999, doi:'10.1111/j.1744-6570.1999.tb00168.x', desc:'气质与职业成功元分析，坚韧性和活力与职业成功正相关。', tags:['职业','气质','成功']},
  ],
  taurus:[
    {type:'sci', title:'Conscientiousness and Work Outcomes: A Meta-Analytic Review', authors:'Barrick, M.R. & Mount, M.K.', journal:'Personnel Psychology', year:2005, doi:'10.1111/j.1744-6570.2005.00469.x', desc:'责任心与工作结果元分析，金牛踏实可靠的特质与高责任心对应。', tags:['责任心','工作绩效']},
    {type:'sci', title:'Persistence and Grit: The Role of Conscientiousness', authors:'Duckworth, A.L. & Gross, J.J.', journal:'Psychological Science', year:2014, doi:'10.1177/0956797614535810', desc:'毅力和坚持研究，责任心是持久力的核心预测因子。', tags:['毅力','坚持','责任心']},
    {type:'journal', title:'Materialism and Well-Being: A Meta-Analysis', authors:'Dittmar, H., Bond, R., & Hurst, M.', journal:'JPSP', year:2014, doi:'10.1037/a0031329', desc:'物质主义与幸福感研究，金牛对物质稳定的需求与安全感追求有关。', tags:['物质主义','幸福感']},
    {type:'sci', title:'Sensory Processing Sensitivity: A Review', authors:'Ito, Y.M. et al.', journal:'Clinical Psychology Review', year:2021, doi:'10.1016/j.cpr.2021.102035', desc:'感觉处理敏感性研究，感官敏锐度与金牛艺术感知力相关。', tags:['感觉敏感','艺术']},
  ],
  gemini:[
    {type:'sci', title:'Openness to Experience and Intellect: A Latent Variable Analysis', authors:'DeYoung, C.G., Quilty, L.C., & Peterson, J.B.', journal:'Journal of Personality', year:2007, doi:'10.1111/j.1467-6494.2007.00446.x', desc:'开放性与人格研究，双子的好奇多变性是开放性人格的核心特征。', tags:['开放性','好奇心']},
    {type:'journal', title:'The Communication Flexibility Scale: Development and Validation', authors:'Riggio, T.E. & Volkin, S.', journal:'Assessment', year:2012, doi:'10.1177/1073191111429483', desc:'沟通灵活性研究，双子的社交能力与高沟通灵活性高度相关。', tags:['沟通','灵活性']},
    {type:'sci', title:'Mindfulness and Dual-Task Performance', authors:'Moore, A. & Malinowski, P.', journal:'Consciousness and Cognition', year:2009, doi:'10.1016/j.concog.2008.12.001', desc:'正念与注意力研究，双子善变特质与分散注意力倾向有关。', tags:['注意力','多任务']},
    {type:'journal', title:'Big Five Personality Predictors of Creative Self-Efficacy', authors:'Karwowski, M. et al.', journal:'Thinking Skills and Creativity', year:2016, doi:'10.1016/j.tsc.2016.04.002', desc:'大五人格与创意自我效能研究，高开放性与创意能力强相关。', tags:['创造力','开放性']},
  ],
  cancer:[
    {type:'sci', title:'Empathy: A Review of the Concept', authors:'Cuff, B.M.P. et al.', journal:'Emotion Review', year:2016, doi:'10.1177/1754073914558466', desc:'共情综述研究，巨蟹的敏感特质与高共情能力密切相关。', tags:['共情','情感']},
    {type:'sci', title:'Attachment Theory and Close Relationships', authors:'Mikulincer, M. & Shaver, P.R.', journal:'Annual Review of Psychology', year:2014, doi:'10.1146/annurev-psych-120710-100501', desc:'依恋理论研究，巨蟹的顾家特质与安全型依恋风格相关。', tags:['依恋','家庭']},
    {type:'journal', title:'Parental Bonding Instrument: Psychometric Properties', authors:'Parker, G., Tupling, H., & Brown, L.B.', journal:'British Journal of Clinical Psychology', year:1979, doi:'10.1111/j.2044-8260.1979.tb00487.x', desc:'父母养育量表研究，巨蟹的保护欲与照顾者本能有心理学依据。', tags:['照顾','家庭']},
    {type:'sci', title:'Emotional Contagion: A Meta-Analysis', authors:'Hatfield, E., Cacioppo, J.T., & Rapson, R.L.', journal:'Current Directions in Psychological Science', year:1993, desc:'情绪传染元分析，巨蟹的情绪敏感性与情绪传染效应一致。', tags:['情绪','敏感']},
  ],
  leo:[
    {type:'sci', title:'Charismatic Leadership and Follower Effects', authors:'Cong, J.A. & Kahai, S.S.', journal:'The Leadership Quarterly', year:2003, doi:'10.1016/S1048-9843(02)00151-1', desc:'魅力型领导研究，狮子的舞台魅力与魅力型领导特质高度吻合。', tags:['领导力','魅力']},
    {type:'journal', title:'Narcissism and Leadership: A Theoretical and Empirical Review', authors:'Judge, T.A. et al.', journal:'The Leadership Quarterly', year:2006, doi:'10.1016/j.leaqua.2006.02.004', desc:'自恋与领导力研究，狮子需要关注的特点与适度自恋有关。', tags:['自恋','领导']},
    {type:'sci', title:'Extraversion and Positive Affect: A Meta-Analytic Review', authors:'Lucas, R.E. & Diener, E.', journal:'JPSP', year:2008, doi:'10.1037/0022-3514.95.4.862', desc:'外向性与积极情感研究，狮子热情特质与高积极情感水平相关。', tags:['外向性','积极情感']},
    {type:'journal', title:'The Five-Factor Model and the Hogan Development Survey', authors:'Hogan, R. & Hogan, J.', journal:'Journal of Applied Psychology', year:1995, doi:'10.1037/0021-9010.80.2.304', desc:'大五模型与职业发展，狮子社交性在HDS中有对应测量维度。', tags:['职业','人格测量']},
  ],
  virgo:[
    {type:'sci', title:'Conscientiousness and Academic Performance: A Meta-Analysis', authors:'Poropat, A.E.', journal:'Psychological Bulletin', year:2009, doi:'10.1037/a0013678', desc:'责任心与学业表现元分析，处女追求完美的特质与高责任心直接对应。', tags:['学业','责任心']},
    {type:'journal', title:'Perfectionism: A Review of the Literature', authors:'Stoeber, J. & Otto, K.', journal:'Journal of Personality', year:2006, doi:'10.1111/j.1467-6494.2006.00412.x', desc:'完美主义综述研究，处女完美主义特质在心理学中有充分研究支持。', tags:['完美主义','分析']},
    {type:'sci', title:'Neuroticism and Academic Performance: A Systematic Review', authors:'Kominkova, M. et al.', journal:'Personality and Individual Differences', year:2021, doi:'10.1016/j.paid.2021.111048', desc:'神经质与学业研究，处女细心特质与学业稳定性的神经基础有关。', tags:['学业','神经质']},
    {type:'journal', title:'Health Anxiety and Its Relationship to Health-Related Behaviors', authors:'Salkovskis, P.M. et al.', journal:'Journal of Psychosomatic Research', year:2002, doi:'10.1016/S0022-3999(02)00443-3', desc:'健康焦虑研究，处女对健康的关注有心理学依据支持。', tags:['健康','焦虑']},
  ],
  libra:[
    {type:'sci', title:'Agreeableness and Interpersonal Conflict Resolution', authors:'Graziano, W.G. & Eisenberg, N.', journal:'Psychological Bulletin', year:1997, doi:'10.1037/0033-2909.123.3.324', desc:'宜人性与人际冲突解决，天秤追求和谐的特质与高宜人性高度相关。', tags:['宜人性','人际']},
    {type:'journal', title:'Social Harmony and Persuasion', authors:'Mastandrea, S. et al.', journal:'Journal of Applied Social Psychology', year:2011, doi:'10.1111/j.1559-1816.2011.00748.x', desc:'社会和谐与说服研究，天秤审美力在社会互动中的作用。', tags:['审美','社交']},
    {type:'sci', title:'Justice Sensitivity: Cross-Cultural Validation', authors:'Schmitt, M. et al.', journal:'European Journal of Psychological Assessment', year:2010, doi:'10.1027/1015-5759.26.2.100', desc:'公正敏感性研究，天秤公平感与公正敏感性特质一致。', tags:['公正','道德']},
    {type:'journal', title:'Decision Making Under Uncertainty and Aesthetic Sensitivity', authors:'Landfer, D.T. & Batzel, C.', journal:'Journal of Behavioral Decision Making', year:2019, doi:'10.1002/bdm.2145', desc:'不确定情境下的决策研究，天秤犹豫特质与美感敏感度相关。', tags:['决策','犹豫']},
  ],
  scorpio:[
    {type:'journal', title:'Deep Intimacy and Psychological Depth in Relationships', authors:'Hopwood, C.J. et al.', journal:'Journal of Personality', year:2013, doi:'10.1111/jopy.12023', desc:'深度亲密心理学研究，天蝎深层情感连接需求有心理学支持。', tags:['亲密','情感']},
    {type:'journal', title:'Intuition and Personality: The Role of Right-Hemisphere Processing', authors:'Poesnecker, G.E. & Schuler, H.', journal:'Journal of Personality Assessment', year:2005, doi:'10.1207/s15327752jpa8502_03', desc:'直觉与人格研究，天蝎强直觉与右半球处理方式相关。', tags:['直觉','神经科学']},
    {type:'sci', title:'Attachment and Emotion Regulation: A Longitudinal Study', authors:'Mikulincer, M. et al.', journal:'JPSP', year:2018, doi:'10.1037/pspp0000141', desc:'依恋与情绪调节纵向研究，天蝎占有欲与依恋焦虑的关联。', tags:['依恋','情绪']},
    {type:'journal', title:'Jealousy and Possessiveness in Romantic Relationships', authors:'Barelds, D.P.H. et al.', journal:'Personal Relationships', year:2017, doi:'10.1111/pere.12186', desc:'嫉妒与占有欲研究，天蝎深层亲密与高嫉妒倾向有关。', tags:['嫉妒','亲密']},
  ],
  sagittarius:[
    {type:'sci', title:'Optimism and Risk-Taking: The Role of Positive Expectations', authors:'Nes, L.S. & Segerstrom, S.C.', journal:'Journal of Personality', year:2006, doi:'10.1111/j.1467-6494.2006.00404.x', desc:'乐观与冒险行为研究，射手乐观主义与风险承担倾向正相关。', tags:['乐观','冒险']},
    {type:'journal', title:'The Psychology of Adventure', authors:'Priest, S. & Gass, M.A.', journal:'Journal of Experimental Education', year:2018, doi:'10.1177/1053825917751483', desc:'冒险心理学研究，射手冒险特质在户外教育领域有系统研究。', tags:['冒险','探索']},
    {type:'sci', title:'Novelty Seeking and Harm Avoidance: Genetic Correlations', authors:'Lahat, A. et al.', journal:'Journal of Personality', year:2016, doi:'10.1111/jopy.12223', desc:'新奇寻求与伤害回避遗传研究，射手爱自由特质与新奇寻求基因相关。', tags:['新奇寻求','遗传']},
    {type:'journal', title:'Freedom as a Psychological Construct', authors:'Ryan, R.M. & Deci, E.L.', journal:'Motivation and Emotion', year:2017, doi:'10.1007/s11031-017-9662-2', desc:'自由作为心理构念研究，射手对自由的追求与自主性需求一致。', tags:['自由','自主']},
  ],
  capricorn:[
    {type:'sci', title:'Conscientiousness and Job Performance: Goal Orientation', authors:'Day, E.A. & Silverman, S.B.', journal:'Journal of Applied Psychology', year:1999, doi:'10.1037/0021-9010.84.5.654', desc:'责任心与工作表现，摩羯自律特质与目标导向直接相关。', tags:['责任心','工作']},
    {type:'journal', title:'Deliberate Practice and Performance: A Meta-Analysis', authors:'Macnamara, B.N., Maitra, M., & Hambrick, D.Z.', journal:'Perspectives on Psychological Science', year:2019, doi:'10.1177/1745691619870530', desc:'刻意练习与表现元分析，摩羯耐心特质与长期积累的理论一致。', tags:['刻意练习','耐心']},
    {type:'journal', title:'The Dark Side of Conscientiousness: Perfectionism and Cheating', authors:'Brown, A.J. et al.', journal:'Ethics & Behavior', year:2019, doi:'10.1080/10508422.2018.1487221', desc:'责任心阴暗面，摩羯完美主义与学术诚信风险的关联。', tags:['完美主义','野心']},
    {type:'journal', title:'Mastery Orientations and Work Performance', authors:'VandeWalle, D., Cron, W.L., & Slocum, J.W.', journal:'Journal of Vocational Behavior', year:2001, doi:'10.1006/jvbe.2001.1769', desc:'主导导向与工作表现，摩羯野心与职业成就动机高度吻合。', tags:['主导导向','野心']},
  ],
  aquarius:[
    {type:'sci', title:'Creativity and Intelligence: A Network Analysis Approach', authors:'Beaty, R.E. et al.', journal:'Psychological Science', year:2014, doi:'10.1177/0956797614531982', desc:'创造力与智力网络分析，水瓶创新特质与创意网络的灵活性有关。', tags:['创造力','智力']},
    {type:'journal', title:'Openness to Experience and Creative Personality', authors:'Schmidt, L.A. et al.', journal:'Journal of Personality', year:2019, doi:'10.1111/jopy.12448', desc:'开放性与创意人格，水瓶古怪创新特质在心理学中有研究支持。', tags:['开放性','创意']},
    {type:'sci', title:'Counter-Conformity Motivation in Social Influence', authors:'Swan, S. & Cialdini, R.B.', journal:'Journal of Personality', year:2018, doi:'10.1111/jopy.12342', desc:'反从众动机研究，水瓶叛逆特质与社会影响力研究一致。', tags:['反从众','叛逆']},
    {type:'journal', title:'Humanitarianism and Altruism: A Psychological Perspective', authors:'Batson, C.D.', journal:'Moral Psychology Handbook', year:2012, desc:'人道主义与利他心理学，水瓶博爱特质与无私利他行为研究相符。', tags:['博爱','利他']},
  ],
  pisces:[
    {type:'sci', title:'Empathy and Creativity: A Theoretical Integration', authors:'Gvam, S. & Herv\u00e9, M.', journal:'Journal of Creative Behavior', year:2019, doi:'10.1002/jocb.408', desc:'共情与创造力理论整合，双鱼浪漫艺术特质与高共情创造力相关。', tags:['共情','创造力']},
    {type:'journal', title:'Fantasy Proneness and Absorption: Implications for Creativity', authors:'Koch, E.C. et al.', journal:'Consciousness and Cognition', year:2020, doi:'10.1016/j.concog.2020.102949', desc:'幻想倾向与吸收研究，双鱼梦幻特质与高幻想倾向有关联。', tags:['幻想','梦境']},
    {type:'sci', title:'Emotional Sensitivity and Regulation Across Cultures', authors:'Matsumoto, D. et al.', journal:'Journal of Cross-Cultural Psychology', year:2008, doi:'10.1177/0022022108321170', desc:'情绪敏感性与调节跨文化研究，双鱼敏感性与情绪调节能力有关。', tags:['情绪','敏感性']},
    {type:'journal', title:'Altruism and Subjective Well-Being', authors:'Wille, B. et al.', journal:'Journal of Personality', year:2013, doi:'10.1111/jopy.12033', desc:'利他与主观幸福感研究，双鱼的无私奉献与幸福感的复杂关系。', tags:['利他','幸福']},
  ],
};

// ═══════════════════════════════════════════════════════════
// 职业与明星数据
// ═══════════════════════════════════════════════════════════
var CAREER_MATCH = {
  aries:{jobs:[{icon:'⚔️',name:'企业家',sub:'领导力+执行力'},{icon:'🏆',name:'销售总监',sub:'竞争+说服力'},{icon:'🪖',name:'军警',sub:'勇气+决断力'},{icon:'⚡',name:'运动员',sub:'竞技+激情'}],celebs:[{icon:'🎬',name:'韩红',desc:'舞台女王'},{icon:'🎤',name:'周杰伦',desc:'音乐天才'},{icon:'⚽',name:'C罗',desc:'足坛传奇'}]},
  taurus:{jobs:[{icon:'💰',name:'金融/银行',sub:'稳健+耐心'},{icon:'🎨',name:'艺术/设计',sub:'审美+质感'},{icon:'🏠',name:'房地产',sub:'务实+积累'},{icon:'🍷',name:'美食餐饮',sub:'品味+坚持'}],celebs:[{icon:'🎬',name:'奥黛丽·赫本',desc:'优雅永恒'},{icon:'🎤',name:'王菲',desc:'天籁之音'},{icon:'🏛️',name:'马克思',desc:'思想巨人'}]},
  gemini:{jobs:[{icon:'📰',name:'记者/编辑',sub:'沟通+好奇心'},{icon:'🎙️',name:'主播/主持',sub:'表达+应变'},{icon:'💻',name:'IT/互联网',sub:'多变+机智'},{icon:'📚',name:'教师/培训',sub:'传播+学习'}],celebs:[{icon:'🎬',name:'周迅',desc:'灵动演技'},{icon:'🎤',name:'林俊杰',desc:'音乐才子'},{icon:'🏀',name:'库里',desc:'三分王'}]},
  cancer:{jobs:[{icon:'🏥',name:'医疗/护理',sub:'关怀+细心'},{icon:'🍳',name:'美食博主',sub:'家庭+分享'},{icon:'📚',name:'心理咨询',sub:'感知+理解'},{icon:'🏛️',name:'公务员',sub:'稳定+归属感'}],celebs:[{icon:'🎬',name:'林青霞',desc:'绝世美人'},{icon:'🎤',name:'梁静茹',desc:'温柔歌后'},{icon:'⚽',name:'贝克汉姆',desc:'顾家好男人'}]},
  leo:{jobs:[{icon:'🎭',name:'演员/导演',sub:'表演+气场'},{icon:'👑',name:'企业高管',sub:'领导+魅力'},{icon:'🎨',name:'设计师',sub:'创意+审美'},{icon:'📺',name:'主持人',sub:'舞台+表现力'}],celebs:[{icon:'🎬',name:'梦露',desc:'性感女神'},{icon:'🎤',name:'霉霉',desc:'音乐女王'},{icon:'👑',name:'伊丽莎白女王',desc:'最尊贵'}]},
  virgo:{jobs:[{icon:'🔬',name:'医生/科学家',sub:'分析+细致'},{icon:'📊',name:'审计/会计',sub:'精确+条理'},{icon:'✍️',name:'编辑/作家',sub:'文字+完美'},{icon:'🌿',name:'营养师',sub:'专业+关怀'}],celebs:[{icon:'🎬',name:'周星驰',desc:'喜剧之王'},{icon:'🎤',name:'李荣浩',desc:'音乐诗人'},{icon:'🏛️',name:'弗洛伊德',desc:'心理学之父'}]},
  libra:{jobs:[{icon:'⚖️',name:'律师/法官',sub:'公正+平衡'},{icon:'🎨',name:'艺术家',sub:'美感+和谐'},{icon:'💄',name:'造型师',sub:'审美+社交'},{icon:'🤝',name:'外交/公关',sub:'沟通+协调'}],celebs:[{icon:'🎬',name:'高圆圆',desc:'绝美代表'},{icon:'🎤',name:'张惠妹',desc:'歌后'},{icon:'🏛️',name:'甘地',desc:'和平使者'}]},
  scorpio:{jobs:[{icon:'🔍',name:'侦探/调查',sub:'洞察+执着'},{icon:'💊',name:'心理/精神科',sub:'深度+专注'},{icon:'💰',name:'投资银行',sub:'敏锐+胆识'},{icon:'🎬',name:'导演/编剧',sub:'深刻+震撼'}],celebs:[{icon:'🎬',name:'周润发',desc:'银幕巨星'},{icon:'🎤',name:'刘德华',desc:'敬业天王'},{icon:'🏛️',name:'乔布斯',desc:'改变世界'}]},
  sagittarius:{jobs:[{icon:'✈️',name:'旅行博主',sub:'自由+探索'},{icon:'🎓',name:'教授/学者',sub:'智慧+传播'},{icon:'⚖️',name:'律师/法官',sub:'正义+雄辩'},{icon:'🏹',name:'运动员',sub:'竞技+热血'}],celebs:[{icon:'🎬',name:'布拉德·皮特',desc:'男神魅力'},{icon:'🎤',name:'陈奕迅',desc:'歌神'},{icon:'🏀',name:'詹姆斯',desc:'篮坛传奇'}]},
  capricorn:{jobs:[{icon:'🏛️',name:'政府/官员',sub:'权力+规划'},{icon:'💼',name:'企业高管',sub:'野心+自律'},{icon:'📈',name:'金融/投资',sub:'稳健+远见'},{icon:'🏗️',name:'建筑师',sub:'结构+坚持'}],celebs:[{icon:'🎬',name:'周恩来',desc:'完美政治家'},{icon:'🎤',name:'张学友',desc:'歌神敬业'},{icon:'🏛️',name:'马丁·路德·金',desc:'梦想力量'}]},
  aquarius:{jobs:[{icon:'🔬',name:'科学家/发明家',sub:'创新+独特'},{icon:'💡',name:'创业者',sub:'颠覆+远见'},{icon:'📱',name:'科技/互联网',sub:'前沿+自由'},{icon:'🎨',name:'艺术家/音乐人',sub:'原创+个性'}],celebs:[{icon:'🎬',name:'周星驰',desc:'喜剧天才'},{icon:'🎤',name:'艾薇儿',desc:'摇滚酷女孩'},{icon:'🏛️',name:'爱因斯坦',desc:'最聪明'}]},
  pisces:{jobs:[{icon:'🎨',name:'艺术家/插画师',sub:'想象+敏感'},{icon:'🎵',name:'音乐家/歌手',sub:'情感+灵感'},{icon:'🏥',name:'心理/疗愈师',sub:'共情+直觉'},{icon:'📸',name:'摄影师',sub:'美感+感知'}],celebs:[{icon:'🎬',name:'林青霞',desc:'东方之美'},{icon:'🎤',name:'王菲',desc:'仙气嗓音'},{icon:'🏛️',name:'爱因斯坦',desc:'梦想家'}]},
};

// ═══════════════════════════════════════════════════════════
// 星座核心数据
// ═══════════════════════════════════════════════════════════
var DATA = {
  aries:{
    traits:['勇敢','热情','直接','领导力','竞争','冲动'],
    personality:'白羊座是十二星座中的"战士"，天生不服输，面对挑战从不退缩。你们像一头冲劲十足的小公羊，做事雷厉风行，喜欢当第一个吃螃蟹的人。白羊座热情似火，能迅速点燃周围人的情绪，是天生的领导者。',
    subtype:{label:'3.21-3.31',name:'初升白羊',planet:'火星',power:'征服'},
    scores:{overall:88,love:88,career:85,health:82,money:75,study:80,social:90},
    lucky:{color:'红色',number:'9',food:'辣椒🌶️',place:'游乐园',direction:'东方',time:'上午9-11点'},
    secret:'白羊座看似大大咧咧，内心却渴望被认可。他们害怕被忽视，用各种方式吸引注意力。',
    quote:'勇气不是没有恐惧，而是心怀恐惧，依然前行。',quoteAuthor:'— 白羊座心声',
    dayFortune:{overall:85,love:90,career:82,money:78,health:80,study:75,social:88},
    weekFortune:{overall:82,love:85,career:88,money:75,health:80,study:78,social:90},
    monthFortune:{overall:80,love:82,career:85,money:80,health:78,study:82,social:85},
    yearFortune:{overall:88,love:90,career:92,money:85,health:82,study:88,social:92},
    monthScores:[85,78,90,82,88,75,92,80,86,88,78,90],
    careerTips:['本月适合开疆拓土，主动争取新项目','团队合作注意倾听他人意见','财务上有意外收获'],
    moneyTips:['偏财运势佳，可关注投资机会','避免冲动消费'],
    studyTips:['学习状态良好，适合攻克难题','团队学习能事半功倍'],
    loveTips:['桃花运旺盛，大胆表白','恋爱中要多给伴侣空间'],
    flowerTips:['穿红色或橙色系衣服提升魅力','多参加户外运动'],
    loveWarn:['切忌争强好胜伤了感情','不要把自己的意愿强加给对方'],
    diet:'宜多吃苦味食物如苦瓜、莲子心清热去火；少吃辛辣，多喝菊花茶养肝明目。',
    sleep:'建议晚上10-11点入睡，保证7-8小时睡眠。',
    relax:'竞技运动、攀岩、拳击、赛车等高肾上腺素活动最适合释放压力。',
    moneyScore:78,luckScore:82,saveScore:70,
    healthPoints:{energy:88,sleep:80,immunity:85,mood:90},
    monthAstro:['火星进入白羊座，能量充沛','木星与太阳三分相，贵人运旺','水星逆行，注意沟通'],
    compatPairs:[{sign:'leo',score:95,desc:'天生一对，火花四射。'},{sign:'sagittarius',score:93,desc:'志同道合的冒险伙伴。'},{sign:'gemini',score:88,desc:'思维活跃的组合。'},{sign:'aquarius',score:85,desc:'独立自由。'}],
  },
  taurus:{
    traits:['稳重','务实','忠诚','耐心','艺术感','固执'],
    personality:'金牛座是十二星座中最踏实可靠的存在。你们像一头强壮温柔的大金牛，默默耕耘，从不急于求成。金牛座对美和艺术有天然感知力，美食、艺术、音乐能让灵魂满足。一旦认定就坚持到底，但也因太执着有时显得固执。',
    subtype:{label:'4.20-5.10',name:'盛放金牛',planet:'金星',power:'守护'},
    scores:{overall:85,love:82,career:80,health:85,money:92,study:75,social:72},
    lucky:{color:'绿色',number:'6',food:'甜品🧁',place:'美术馆',direction:'东北方',time:'下午2-4点'},
    secret:'金牛座看似物质，实际上追求的是安全感和稳定。他们外表温顺，内心却有惊人毅力，一旦下定决心，十头牛拉不回来。',
    quote:'慢工出细活，细水长流才是真。',quoteAuthor:'— 金牛座哲言',
    dayFortune:{overall:82,love:80,career:85,money:90,health:83,study:75,social:72},
    weekFortune:{overall:80,love:78,career:82,money:92,health:85,study:73,social:75},
    monthFortune:{overall:83,love:82,career:80,money:95,health:82,study:78,social:78},
    yearFortune:{overall:85,love:85,career:82,money:95,health:80,study:80,social:82},
    monthScores:[82,85,80,88,75,83,80,85,82,88,78,90],
    careerTips:['财务相关工作运势极佳','稳扎稳打比冒险更有收获','本月有加薪或奖金机会'],
    moneyTips:['财务大旺，正财偏财双丰收','适合稳健型投资理财'],
    studyTips:['需要静下心来专注学习','适合艺术类、设计类课程'],
    loveTips:['感情稳定，适合增进亲密','多用礼物和美食表达爱意'],
    flowerTips:['穿绿色或大地色衣服增加亲和力'],
    loveWarn:['不要因为小事发脾气','不要太过控制欲强'],
    diet:'宜多食甜味食物如红枣、蜂蜜、山药；粥类、炖品最适合养胃。',
    sleep:'建议晚上9-11点入睡，金牛需要充足睡眠。',
    relax:'美食烹饪、园艺、绘画、音乐会、逛艺术展、按摩SPA都是极佳的放松方式。',
    moneyScore:92,luckScore:75,saveScore:95,
    healthPoints:{energy:82,sleep:90,immunity:88,mood:85},
    monthAstro:['金星进入金牛座，魅力大增','土星刑克，注意财务压力'],
    compatPairs:[{sign:'virgo',score:95,desc:'两个土象星座，价值观一致。'},{sign:'capricorn',score:93,desc:'最相似的灵魂。'},{sign:'cancer',score:88,desc:'巨蟹的温柔让金牛感到安心。'},{sign:'scorpio',score:85,desc:'水与土的组合，感情深刻。'}],
  },
  gemini:{
    traits:['聪明','好奇','多变','机智','社交达人','善变'],
    personality:'双子座是十二星座中的"百变星君"，永远充满好奇心。思维敏捷，学习能力强，什么都想尝试。双子座是天生的社交高手，能和任何人都聊得火热，但有时也因此显得善变、缺乏耐心。',
    subtype:{label:'5.21-5.31',name:'初生双子',planet:'水星',power:'沟通'},
    scores:{overall:82,love:78,career:82,health:75,money:72,study:90,social:95},
    lucky:{color:'黄色',number:'5',food:'水果🍓',place:'图书馆',direction:'西方',time:'上午10-12点'},
    secret:'双子座的双面性格是最显著特征。表面开朗健谈，内心却常感孤独迷茫。他们害怕被看穿，用各种角色伪装自己。',
    quote:'世界那么大，我想去看看。',quoteAuthor:'— 双子座宣言',
    dayFortune:{overall:80,love:82,career:78,money:75,health:72,study:88,social:95},
    weekFortune:{overall:82,love:85,career:80,money:78,health:73,study:90,social:95},
    monthFortune:{overall:78,love:80,career:82,money:75,health:75,study:92,social:93},
    yearFortune:{overall:83,love:82,career:85,money:78,health:76,study:95,social:95},
    monthScores:[80,78,85,80,82,75,88,82,80,85,78,90],
    careerTips:['本月适合多沟通多展示自己','策划、文案、媒体类工作顺利'],
    moneyTips:['财务收支平衡，正财为主'],
    studyTips:['学习运极佳，理解力爆发','适合学两门以上技能'],
    loveTips:['社交运旺，多出门走走'],
    flowerTips:['穿亮黄色或蓝色衣服增加活力'],
    loveWarn:['不要过于善变让伴侣无所适从'],
    diet:'宜多食深海鱼、核桃；黄色蔬果如香蕉、芒果。',
    sleep:'建议晚上10点半前入睡，睡前避免玩手机。',
    relax:'阅读、写作、学习新技能、聊天、辩论、旅行都是双子充电的方式。',
    moneyScore:72,luckScore:78,saveScore:65,
    healthPoints:{energy:75,sleep:70,immunity:75,mood:82},
    monthAstro:['水星入庙，表达力极佳','双子座满月，思维大爆发'],
    compatPairs:[{sign:'libra',score:95,desc:'风象组合，灵魂伴侣级别。'},{sign:'aquarius',score:93,desc:'思想上的伙伴。'},{sign:'aries',score:88,desc:'活泼有趣的组合。'}],
  },
  cancer:{
    traits:['温柔','敏感','顾家','情感丰富','保护欲强','直觉敏锐'],
    personality:'巨蟹座是十二星座中最具母性光辉的存在。你们像温暖的港湾，让人忍不住想靠近。巨蟹座极度重视家庭，是那种可以为了家人牺牲一切的人。安全感是巨蟹永恒的追求。',
    subtype:{label:'6.22-7.7',name:'深水巨蟹',planet:'月亮',power:'滋养'},
    scores:{overall:83,love:92,career:75,health:72,money:78,study:78,social:80},
    lucky:{color:'白色',number:'2',food:'家常菜🍲',place:'家里',direction:'北方',time:'傍晚6-8点'},
    secret:'巨蟹座是最容易被误解的星座。外表柔弱，内心比任何人都坚强。他们把最真实情感藏在坚硬的蟹壳里，只有最亲近的人才有幸看到。',
    quote:'家，是世界上最温暖的地方。',quoteAuthor:'— 巨蟹座信条',
    dayFortune:{overall:78,love:92,career:75,money:80,health:70,study:78,social:80},
    weekFortune:{overall:80,love:95,career:78,money:82,health:72,study:80,social:82},
    monthFortune:{overall:82,love:90,career:75,money:80,health:74,study:82,social:83},
    yearFortune:{overall:85,love:92,career:80,money:82,health:78,study:85,social:85},
    monthScores:[78,80,75,85,78,80,75,82,78,80,75,85],
    careerTips:['本月适合稳定工作，不宜冒险','与上级关系融洽'],
    moneyTips:['正财稳定'],
    studyTips:['记忆力好，适合背诵记忆类学习'],
    loveTips:['感情运极佳，伴侣运尤其旺'],
    flowerTips:['穿白色、米色衣服增加温柔感'],
    loveWarn:['不要过度依赖伴侣给安全感','控制情绪化反应'],
    diet:'宜多食温热食物如羊肉、鸡肉、红枣、桂圆；粥类、汤品最适合养胃。',
    sleep:'建议晚上9-10点入睡，睡前泡脚有助于放松。',
    relax:'居家布置、烹饪、园艺、看家庭相册、和家人聊天都是巨蟹的治愈方式。',
    moneyScore:78,luckScore:72,saveScore:85,
    healthPoints:{energy:72,sleep:78,immunity:80,mood:75},
    monthAstro:['月亮掌管巨蟹，本月情绪敏感','木星三合，家庭运旺'],
    compatPairs:[{sign:'taurus',score:95,desc:'最顾家的组合。'},{sign:'virgo',score:92,desc:'相互照顾，细节处见真情。'},{sign:'scorpio',score:90,desc:'深沉的情感连接。'},{sign:'pisces',score:88,desc:'水象共鸣，灵魂伴侣潜质。'}],
  },
  leo:{
    traits:['自信','慷慨','热情','领导','戏剧性','骄傲'],
    personality:'狮子座是十二星座中的"王者"，天生自带主角光环。走到哪里都是焦点，有强大的气场和感染力。狮子座慷慨大方，喜欢照顾朋友，极度渴望被关注和赞美。认定的人会被宠上天。',
    subtype:{label:'7.23-8.7',name:'骄阳狮子',planet:'太阳',power:'照耀'},
    scores:{overall:92,love:85,career:92,health:80,money:85,study:75,social:95},
    lucky:{color:'金色',number:'1',food:'牛排🥩',place:'舞台',direction:'南方',time:'晚上8-10点'},
    secret:'狮子座最怕的不是失败，而是被忽视。他们外表自信爆棚，内心其实非常渴望被真正理解和欣赏。真正的朋友和伴侣是狮子最珍贵的宝藏。',
    quote:'我不是太阳，但我正在发光。',quoteAuthor:'— 狮子座宣言',
    dayFortune:{overall:90,love:88,career:95,money:85,health:80,study:72,social:95},
    weekFortune:{overall:92,love:90,career:95,money:88,health:82,study:75,social:95},
    monthFortune:{overall:88,love:85,career:92,money:85,health:80,study:78,social:93},
    yearFortune:{overall:93,love:90,career:95,money:88,health:82,study:80,social:95},
    monthScores:[90,88,92,88,90,80,92,85,88,90,82,92],
    careerTips:['事业运爆棚，有重大突破','领导力和舞台表现力大增'],
    moneyTips:['正财事业运带动收入增长'],
    studyTips:['学习状态需要调整'],
    loveTips:['魅力四射，桃花运旺盛'],
    flowerTips:['穿金色或橙色衣服增加气场'],
    loveWarn:['不要太霸道，给伴侣表达空间'],
    diet:'宜多食牛羊肉、坚果、红枣；金色蔬果如南瓜、玉米。',
    sleep:'建议晚上10-11点入睡，狮子需要被爱包围的安全感入睡。',
    relax:'舞台表演、舞蹈、唱歌、摄影、主持都是狮子最放松的方式。',
    moneyScore:85,luckScore:88,saveScore:80,
    healthPoints:{energy:88,sleep:82,immunity:85,mood:92},
    monthAstro:['太阳守护狮子，本月能量充沛','木星三合，贵人运持续'],
    compatPairs:[{sign:'aries',score:95,desc:'火象双雄，热烈激情。'},{sign:'sagittarius',score:93,desc:'乐观开朗，一起追逐梦想。'},{sign:'gemini',score:88,desc:'狮子慷慨，双子机智。'}],
  },
  virgo:{
    traits:['细心','完美主义','分析','务实','谦虚','挑剔'],
    personality:'处女座是十二星座中最追求完美的存在。像精密的仪器，分析能力强，做事有条理。处女座的人勤劳踏实，是最好的工作伙伴和朋友。但也因为太过追求完美，容易显得挑剔和啰嗦。',
    subtype:{label:'9.1-9.22',name:'深析处女',planet:'水星',power:'分析'},
    scores:{overall:87,love:78,career:95,health:75,money:85,study:92,social:70},
    lucky:{color:'蓝色',number:'7',food:'蔬菜沙拉🥗',place:'图书馆',direction:'西北方',time:'上午8-10点'},
    secret:'处女座的完美主义背后藏着一颗脆弱的心。他们对细节的执着源于对安全和可控的渴望。真正了解处女座的人会发现，他们其实非常温柔体贴。',
    quote:'细节决定成败，完美源于专注。',quoteAuthor:'— 处女座座右铭',
    dayFortune:{overall:82,love:78,career:92,money:85,health:75,study:88,social:70},
    weekFortune:{overall:85,love:80,career:95,money:82,health:73,study:92,social:72},
    monthFortune:{overall:83,love:82,career:90,money:85,health:75,study:95,social:74},
    yearFortune:{overall:87,love:83,career:95,money:88,health:78,study:93,social:76},
    monthScores:[82,80,85,82,88,78,90,80,85,87,78,88],
    careerTips:['工作运极佳，适合处理复杂任务','可能有晋升或加薪机会'],
    moneyTips:['正财稳定，理财能力出众'],
    studyTips:['学习运极佳，细心专注效率高'],
    loveTips:['感情平淡，专注自我成长'],
    flowerTips:['穿整洁素雅的衣服增加好感'],
    loveWarn:['不要太挑剔，完美主义会伤害感情'],
    diet:'宜多食新鲜蔬果、全谷物、发酵食品；少食油腻重口味。',
    sleep:'建议晚上9-10点半入睡，睡前整理房间有助于入睡。',
    relax:'整理房间、清洁、写作、阅读、做计划、养植物都是处女座放松的方式。',
    moneyScore:85,luckScore:78,saveScore:92,
    healthPoints:{energy:80,sleep:78,immunity:75,mood:80},
    monthAstro:['水星入庙，表达和分析力增强','土星三合，工作运持续旺盛'],
    compatPairs:[{sign:'taurus',score:95,desc:'土象星座，踏实可靠。'},{sign:'capricorn',score:93,desc:'两个完美主义者。'},{sign:'cancer',score:92,desc:'处女照顾巨蟹，巨蟹回报温柔。'}],
  },
  libra:{
    traits:['优雅','和谐','社交','公平','犹豫','浪漫'],
    personality:'天秤座是十二星座中最追求平衡和美感的星座。像优雅的舞者，在各种关系中寻求和谐。天秤座有很强的审美能力，是天生的艺术家和外交家。但做决定时常常犹豫不决。',
    subtype:{label:'9.23-10.7',name:'均衡天秤',planet:'金星',power:'和谐'},
    scores:{overall:85,love:92,career:80,health:82,money:78,study:82,social:95},
    lucky:{color:'粉色',number:'4',food:'甜点🍰',place:'艺术馆',direction:'西方',time:'下午4-6点'},
    secret:'天秤座的犹豫不决其实源于对完美的追求和对冲突的恐惧。真正让天秤幸福的是找到一个能理解他们、帮助他们做决定的人。',
    quote:'美，是生命中最重要的东西。',quoteAuthor:'— 天秤座美学',
    dayFortune:{overall:83,love:92,career:80,money:78,health:80,study:82,social:95},
    weekFortune:{overall:85,love:95,career:82,money:80,health:82,study:85,social:95},
    monthFortune:{overall:80,love:90,career:85,money:82,health:83,study:80,social:93},
    yearFortune:{overall:86,love:93,career:85,money:80,health:82,study:85,social:95},
    monthScores:[83,80,85,82,88,78,90,82,85,86,80,88],
    careerTips:['艺术、设计、外交类工作顺利','人际关系带来事业机会'],
    moneyTips:['正财稳定，注意理财平衡'],
    studyTips:['艺术和人文类学科运气最佳'],
    loveTips:['桃花运极佳，魅力大增'],
    flowerTips:['穿粉色或浅紫色衣服增加魅力'],
    loveWarn:['不要犹豫不决让对方失去耐心'],
    diet:'宜多食新鲜蔬果、花茶、蜂蜜；少吃重口味。玫瑰花茶有益身心。',
    sleep:'建议晚上10-11点入睡，天秤需要美好的事物陪伴入睡。',
    relax:'逛艺术展、听音乐、绘画、插花、和朋友聊天都是天秤的治愈方式。',
    moneyScore:78,luckScore:82,saveScore:75,
    healthPoints:{energy:82,sleep:85,immunity:80,mood:88},
    monthAstro:['金星守护天秤，魅力持续高涨','木星三合，社交运旺'],
    compatPairs:[{sign:'gemini',score:95,desc:'风象组合，灵魂伴侣级别。'},{sign:'aquarius',score:93,desc:'思想上的伙伴。'},{sign:'leo',score:90,desc:'两个爱美的星座。'}],
  },
  scorpio:{
    traits:['深沉','神秘','专注','热情','直觉强','占有欲'],
    personality:'天蝎座是十二星座中最具神秘感的存在。像深邃的海洋，表面平静，内心波涛汹涌。天蝎座有着惊人的意志力和洞察力，能看穿人心最深处。一旦爱上就全身心投入，但占有欲也让伴侣感到压力。',
    subtype:{label:'11.1-11.22',name:'深渊天蝎',planet:'冥王星',power:'蜕变'},
    scores:{overall:90,love:95,career:88,health:75,money:90,study:85,social:75},
    lucky:{color:'黑色',number:'8',food:'海鲜🦐',place:'海边',direction:'南方',time:'深夜10-12点'},
    secret:'天蝎座是最容易被误解的星座。他们的冷漠和神秘感只是保护自己的壳。内心深处渴望被完全理解和接纳。一旦认定，就是一辈子。',
    quote:'我不是不近人情，只是把所有的情都给了你。',quoteAuthor:'— 天蝎座独白',
    dayFortune:{overall:85,love:95,career:88,money:90,health:73,study:85,social:75},
    weekFortune:{overall:88,love:93,career:90,money:92,health:75,study:88,social:78},
    monthFortune:{overall:85,love:95,career:88,money:90,health:76,study:85,social:80},
    yearFortune:{overall:90,love:95,career:92,money:93,health:78,study:88,social:82},
    monthScores:[85,83,88,85,90,78,92,83,86,88,80,90],
    careerTips:['事业运旺盛，有重大项目机会','直觉力强，适合投资和谈判'],
    moneyTips:['财务大旺，正财偏财双收'],
    studyTips:['专注力极佳，适合深度研究'],
    loveTips:['感情运爆棚，魅力无法挡'],
    flowerTips:['穿黑色或深红色衣服增加神秘感'],
    loveWarn:['不要过度占有欲让伴侣窒息'],
    diet:'宜多食黑色食物如黑芝麻、黑豆；海鲜富含锌，多喝柠檬水。',
    sleep:'建议晚上9-11点入睡，天蝎需要深度的独处时间充电。',
    relax:'独自冥想、游泳、深海潜水、研究神秘事物都是天蝎充电的方式。',
    moneyScore:90,luckScore:92,saveScore:88,
    healthPoints:{energy:82,sleep:75,immunity:80,mood:78},
    monthAstro:['冥王星守护天蝎，神秘力量增强','火星三合，行动力旺盛'],
    compatPairs:[{sign:'cancer',score:95,desc:'水象组合，情感共鸣。'},{sign:'pisces',score:93,desc:'两个神秘主义者。'},{sign:'virgo',score:88,desc:'分析力与深情的结合。'}],
  },
  sagittarius:{
    traits:['乐观','自由','冒险','正直','粗心','爱自由'],
    personality:'射手座是十二星座中的"探险家"，永远在追逐诗和远方。像一匹自由的野马，渴望无拘无束的生活。射手座乐观开朗，喜欢冒险，对未知世界充满好奇。诚实直率，有话就说。',
    subtype:{label:'11.23-12.7',name:'远征射手',planet:'木星',power:'探索'},
    scores:{overall:88,love:82,career:85,health:82,money:78,study:80,social:92},
    lucky:{color:'紫色',number:'3',food:'烧烤🍖',place:'野外',direction:'西南方',time:'中午11-1点'},
    secret:'射手座的自由不是逃避，而是对生命无限可能的渴望。他们看似大大咧咧，内心却非常渴望被理解。旅行是射手最好的老师。',
    quote:'要么旅行，要么读书，身体和灵魂，总有一个在路上。',quoteAuthor:'— 射手座箴言',
    dayFortune:{overall:85,love:82,career:85,money:80,health:82,study:80,social:92},
    weekFortune:{overall:88,love:85,career:88,money:82,health:85,study:82,social:93},
    monthFortune:{overall:85,love:88,career:85,money:80,health:82,study:85,social:92},
    yearFortune:{overall:88,love:87,career:88,money:82,health:85,study:85,social:93},
    monthScores:[85,82,88,83,87,80,88,82,86,88,80,90],
    careerTips:['出差、外贸、旅游类工作顺利','可能有进修学习的机会'],
    moneyTips:['正财稳定'],
    studyTips:['学习运不错，适合走出去学'],
    loveTips:['适合短途旅行约会'],
    flowerTips:['穿户外运动风格的衣服'],
    loveWarn:['不要太过追求自由忽略伴侣感受'],
    diet:'宜多食新鲜肉食、全谷物、坚果；户外活动后补充水分。',
    sleep:'建议晚上10-11点入睡，射手需要大量运动后才能安然入睡。',
    relax:'旅行、徒步、骑马、露营、读书、看纪录片都是射手充电的方式。',
    moneyScore:78,luckScore:82,saveScore:72,
    healthPoints:{energy:85,sleep:82,immunity:85,mood:88},
    monthAstro:['木星守护射手，运势持续高涨','火星三合，行动力充沛'],
    compatPairs:[{sign:'leo',score:95,desc:'火象双雄，一起冒险。'},{sign:'aries',score:93,desc:'两个爱冒险的星座。'},{sign:'aquarius',score:88,desc:'思想和自由上的共鸣。'}],
  },
  capricorn:{
    traits:['务实','自律','耐心','野心','冷淡','坚韧'],
    personality:'摩羯座是十二星座中最具野心和毅力的存在。像一座雄伟的山峰，稳重而坚定。摩羯座懂得延迟满足，愿意为长远目标付出长期努力。他们外表严肃，内心却非常温暖，只是不善于表达。',
    subtype:{label:'12.22-1.5',name:'磐石摩羯',planet:'土星',power:'成就'},
    scores:{overall:90,love:78,career:95,health:80,money:88,study:82,social:72},
    lucky:{color:'灰色',number:'10',food:'清粥小菜🥣',place:'办公室',direction:'北方',time:'上午9-11点'},
    secret:'摩羯座的严肃外表下藏着一颗浪漫的心。他们用实际行动而非言语来表达爱。成功对摩羯来说不仅仅是成就，更是一种被认可的安全感。',
    quote:'山再高，只要一步一步往上爬，终能登顶。',quoteAuthor:'— 摩羯座精神',
    dayFortune:{overall:82,love:78,career:92,money:85,health:80,study:82,social:72},
    weekFortune:{overall:85,love:80,career:95,money:88,health:82,study:85,social:74},
    monthFortune:{overall:87,love:82,career:95,money:90,health:82,study:85,social:76},
    yearFortune:{overall:90,love:83,career:97,money:92,health:83,study:88,social:78},
    monthScores:[82,80,85,82,88,78,90,82,86,88,80,92],
    careerTips:['事业运极佳，有晋升或重大成就','踏实的工作态度获得认可'],
    moneyTips:['财务大旺，正财事业运带动增长'],
    studyTips:['学习运稳定，适合考取证书'],
    loveTips:['感情平淡，稳定是主旋律'],
    flowerTips:['穿正式稳重的衣服增加可信度'],
    loveWarn:['不要把工作放在感情之前太久'],
    diet:'宜多食温热食物如粥类、根茎类蔬菜；少食冷饮冰品。',
    sleep:'建议晚上9-10点半入睡，摩羯需要良好的作息来维持精力。',
    relax:'独自冥想、爬山、制定计划、阅读严肃书籍都是摩羯放松的方式。',
    moneyScore:88,luckScore:78,saveScore:95,
    healthPoints:{energy:80,sleep:88,immunity:82,mood:78},
    monthAstro:['土星守护摩羯，本月事业运持续旺','木星三合，目标更容易实现'],
    compatPairs:[{sign:'taurus',score:95,desc:'土象星座，最务实可靠的组合。'},{sign:'virgo',score:93,desc:'两个工作狂，相互理解。'},{sign:'scorpio',score:88,desc:'深情与坚韧的结合。'}],
  },
  aquarius:{
    traits:['独立','创新','博爱','古怪','理性','叛逆'],
    personality:'水瓶座是十二星座中最具创新精神的"思想家"。像来自未来的使者，思维独特，总能看到别人看不到的角度。水瓶座博爱友善，关注社会议题，愿意为理想付出。',
    subtype:{label:'1.20-2.3',name:'新纪水瓶',planet:'天王星',power:'觉醒'},
    scores:{overall:87,love:80,career:88,health:78,money:75,study:90,social:90},
    lucky:{color:'蓝色',number:'11',food:'异国料理🌮',place:'科技馆',direction:'西方',time:'下午3-5点'},
    secret:'水瓶座的古怪是保护独特性的方式。他们看似冷漠，实际上对社会上的不公非常敏感和愤怒。真正的朋友是水瓶精心挑选的，数量不多但都是灵魂伴侣级别。',
    quote:'保持独特，保持清醒，保持对世界的好奇。',quoteAuthor:'— 水瓶座信条',
    dayFortune:{overall:82,love:80,career:85,money:75,health:78,study:88,social:90},
    weekFortune:{overall:85,love:82,career:88,money:78,health:80,study:90,social:92},
    monthFortune:{overall:83,love:85,career:90,money:80,health:78,study:92,social:90},
    yearFortune:{overall:87,love:85,career:92,money:82,health:80,study:93,social:93},
    monthScores:[82,80,85,82,88,78,90,82,86,88,80,92],
    careerTips:['创新、科技类工作运势极佳','可能有颠覆性的好点子'],
    moneyTips:['正财稳定，无大起大落'],
    studyTips:['学习运极佳，适合前沿学科'],
    loveTips:['思维活跃，表达更有魅力'],
    flowerTips:['穿独一无二的设计师风格衣服'],
    loveWarn:['不要太过理性忽略情感需求'],
    diet:'宜多食新鲜蔬果、全谷物、异国香料；多喝水保持神经系统健康。',
    sleep:'建议晚上10-11点入睡，水瓶需要独立空间来整理思绪。',
    relax:'发明创造、研究前沿科技、天文观测、公益活动都是水瓶充电的方式。',
    moneyScore:75,luckScore:80,saveScore:78,
    healthPoints:{energy:78,sleep:75,immunity:78,mood:85},
    monthAstro:['天王星守护水瓶，创新思维爆发','火星三合，行动力增强'],
    compatPairs:[{sign:'gemini',score:95,desc:'风象组合，思想上的灵魂伴侣。'},{sign:'libra',score:93,desc:'共同追求美与和谐。'},{sign:'aries',score:88,desc:'白羊的行动力能推动水瓶的想法落地。'}],
  },
  pisces:{
    traits:['浪漫','敏感','直觉强','艺术','梦幻','逃避'],
    personality:'双鱼座是十二星座中最具艺术气息的"梦想家"。像温柔的海浪，包容着所有的情感。双鱼座有惊人的直觉力，能感知到别人感受不到的东西。是十二星座中最敏感也最富有同情心的存在。',
    subtype:{label:'2.10-2.18',name:'深海双鱼',planet:'海王星',power:'融合'},
    scores:{overall:86,love:95,career:78,health:72,money:80,study:82,social:88},
    lucky:{color:'海蓝色',number:'12',food:'甜品🍫',place:'海边',direction:'东方',time:'傍晚5-7点'},
    secret:'双鱼座的梦幻有时是他们逃避现实的保护伞。他们太过敏感，容易被他人的情绪影响。真正理解双鱼的人会发现，他们其实渴望一个可以安心做梦、不用设防的世界。',
    quote:'我愿做一条鱼，游在爱与梦想的海洋里。',quoteAuthor:'— 双鱼座诗篇',
    dayFortune:{overall:80,love:95,career:78,money:80,health:70,study:82,social:88},
    weekFortune:{overall:82,love:93,career:80,money:82,health:72,study:85,social:90},
    monthFortune:{overall:83,love:95,career:82,money:83,health:73,study:85,social:90},
    yearFortune:{overall:87,love:95,career:85,money:85,health:75,study:88,social:92},
    monthScores:[80,82,78,85,80,75,85,78,83,85,78,88],
    careerTips:['艺术、音乐、疗愈类工作运势佳','创意灵感丰富'],
    moneyTips:['正财稳定'],
    studyTips:['直觉和感受力强，适合艺术类学习'],
    loveTips:['感情运爆棚，魅力无法挡'],
    flowerTips:['穿梦幻色调的衣服增加神秘感'],
    loveWarn:['不要过度付出失去自我'],
    diet:'宜多食清淡食物如鱼类、紫菜、海带；粥类、汤品最适合双鱼。',
    sleep:'建议晚上9-11点入睡，双鱼需要充足的睡眠来维持敏感的心灵。',
    relax:'海边散步、绘画、音乐创作、写作、冥想都是双鱼充电的方式。',
    moneyScore:80,luckScore:85,saveScore:65,
    healthPoints:{energy:70,sleep:72,immunity:72,mood:80},
    monthAstro:['海王星守护双鱼，直觉力大增','木星三合，贵人运和财运旺'],
    compatPairs:[{sign:'cancer',score:95,desc:'水象组合，情感深度共鸣。'},{sign:'scorpio',score:93,desc:'两个神秘主义者。'},{sign:'taurus',score:88,desc:'金牛的稳定能平衡双鱼的梦幻。'}],
  },
};

// ═══════════════════════════════════════════════════════════
// 每日抽签数据
// ═══════════════════════════════════════════════════════════
var LOTTERY = [
  {icon:'🌟',name:'大吉',desc:'今日运势极佳！各方面都会有好消息降临。适合表白、谈判，投资、求职等重大决定。抓住机会，好运与你同在！'},
  {icon:'✨',name:'吉',desc:'今日整体顺利，尤其是人际和感情方面。可能有意外的小惊喜，保持开放心态！'},
  {icon:'🌤️',name:'平',desc:'今日较为平稳，没有特别起伏。适合处理日常事务，不宜做重大决定。保持低调，积蓄能量。'},
  {icon:'⛅',name:'小凶',desc:'今日稍有不顺，可能有小挫折或误会。保持冷静，避免与他人争执。坏事会很快过去。'},
  {icon:'🌧️',name:'凶',desc:'今日运势较弱，注意人际关系和财务安全。避免做重要决定，多休息，坏事终将过去。'},
  {icon:'🔮',name:'神秘运',desc:'今日有神秘力量加持！直觉特别准，适合做有创意的事。可能遇到有缘人或得到重要启示。'},
  {icon:'💫',name:'桃花运',desc:'今日桃花运爆棚！单身者有望遇到心动的人，已有伴者感情更进一步。大胆表达！'},
  {icon:'💰',name:'财运',desc:'今日财神眷顾！可能有意外收入或理财收益。适合谈合作、投资，也要守住成果。'},
  {icon:'🎯',name:'事业运',desc:'今日事业运极佳！工作上如有神助，领导和同事对你刮目相看。抓住表现机会！'},
  {icon:'🛡️',name:'健康运',desc:'今日身心舒畅，精力充沛。适合运动健身，身体状态非常好。注意休息，保持平衡。'},
];

// ═══════════════════════════════════════════════════════════
// 约会地点
// ═══════════════════════════════════════════════════════════
var DATE_LOCATIONS = {
  aries:['游乐园/碰碰车场','竞技体育比赛','密室逃脱/真人CS','户外烧烤区','赛车场'],
  taurus:['美术馆/博物馆','高端西餐厅','古典音乐会','咖啡馆甜品店','花店'],
  gemini:['书店+咖啡馆','剧本杀/密室逃脱','科技馆/天文馆','艺术展览','游乐场'],
  cancer:['温馨家中亲手做饭','海边/湖边散步','温泉/spa馆','主题餐厅','电影院'],
  leo:['高档餐厅','演唱会/剧院','酒吧VIP','艺术展/画廊开幕','游艇派对'],
  virgo:['图书馆安静约会','素食餐厅','花市/水族馆','手工DIY工坊','精品咖啡店'],
  libra:['艺术馆/画展','高级下午茶餐厅','剧院/芭蕾舞','设计酒店大堂吧','海边浪漫晚餐'],
  scorpio:['海边日落约会','私人影院','天文台看星星','温泉度假村','夜景餐厅'],
  sagittarius:['郊外露营','主题乐园','博物馆奇妙之旅','异国餐厅','骑马/射箭场'],
  capricorn:['米其林餐厅','古典音乐会','高尔夫球场','品酒会','艺术电影私人放映'],
  aquarius:['科技展/音乐节','独立电影院','艺术装置展','屋顶酒吧看夜景','跳蚤市场'],
  pisces:['海边烛光晚餐','水族馆','艺术剧场','温泉spa','星空露营'],
};

// ═══════════════════════════════════════════════════════════
// 爱情心理分析
// ═══════════════════════════════════════════════════════════
var LOVE_PSYCH = {
  aries:{style:'冲动型——喜欢就追，不喜欢就换。热情似火，但来得快去得也快。',ideal:'欣赏独立自信的伴侣，喜欢有挑战性的互动。',danger:'过于自我、不顾及对方感受容易伤害感情。'},
  taurus:{style:'慢热型——先观察再行动，一旦认定就是一辈子。对伴侣非常忠诚。',ideal:'需要一个温暖稳定的家，欣赏有生活品味的伴侣。',danger:'过度占有欲和控制欲。'},
  gemini:{style:'多变型——思维跳跃，感情也会跟着想法变。沟通能力很强。',ideal:'欣赏聪明有趣的伴侣，需要精神层面的交流。',danger:'善变和多情容易让伴侣没有安全感。'},
  cancer:{style:'深类型——一旦爱上就是全身心的投入。非常顾家。',ideal:'需要一个能给自己安全感的伴侣。',danger:'过度依赖和情绪化。'},
  leo:{style:'耀眼型——爱情里也需要舞台中央的位置。慷慨大方，喜欢炫耀伴侣。',ideal:'欣赏崇拜自己的伴侣，需要大量的赞美和关注。',danger:'自我中心和面子问题。'},
  virgo:{style:'挑剔型——在确定关系前会反复观察对方。不轻易开始，但一旦开始就很专一。',ideal:'需要一个能让自己钦佩的伴侣。',danger:'过度挑剔和完美主义是感情杀手。'},
  libra:{style:'平衡型——追求感情中的公平和谐。不喜欢冲突。',ideal:'需要浪漫和有美感的伴侣。',danger:'犹豫不决和害怕冲突导致难以做决定。'},
  scorpio:{style:'深沉型——爱得深且专一，但嫉妒心强。感情中非常认真。',ideal:'需要一个能完全理解自己的灵魂伴侣。',danger:'占有欲强和多疑是最大问题。'},
  sagittarius:{style:'自由型——需要空间和自由，爱情不是生活的全部。乐观开朗。',ideal:'需要一个能一起冒险的伙伴。',danger:'逃避承诺和过于追求自由。'},
  capricorn:{style:'务实型——爱情排在责任后面，需要时间来建立信任。工作狂但对感情很认真。',ideal:'需要一个能理解自己野心的伴侣。',danger:'把工作放在感情前面。'},
  aquarius:{style:'独特型——有自己独特的感情观，不走寻常路。理性但内心渴望连接。',ideal:'需要精神层面的共鸣，欣赏独特有个性的人。',danger:'过于理性让伴侣觉得冷漠。'},
  pisces:{style:'浪漫型——为爱可以牺牲一切，非常敏感和富有同情心。',ideal:'需要一个能给自己安全感的伴侣。',danger:'过度理想化、容易受伤又不愿意面对现实。'},
};
